targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql

    builders:
      artemis:
        options:
          generate_helpers: true

          schema_mapping:
            - schema: graphql/schema.graphql
              queries_glob: graphql/operations.graphql
              output: lib/graphql/graphql_operations_api.dart
            - schema: graphql/ship.schema.graphql
              queries_glob: graphql/ship.query.graphql
              output: lib/graphql/ship_query.dart

          scalar_mapping:
            - graphql_type: Date
              dart_type: DateTime
              use_custom_parser: true
