targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
      - schemaSpaceX.graphql

    builders:
      artemis:
        options:
          generate_helpers: true

          schema_mapping:
            - schema: graphql/schema.graphql
              queries_glob: graphql/operations.graphql
              output: lib/graphql/graphql_operations_api.dart
            - schema: graphql/schemaSpaceX.graphql
              queries_glob: graphql/operationSpaceX.graphql
              output: lib/graphql/graphql_operations_api_SpaceX.dart
          scalar_mapping:
            - graphql_type: Date
              dart_type: DateTime
              use_custom_parser: true
