name: flutter_starter_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_dotenv: ^5.0.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  http: ^0.13.3
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  layout: ^1.0.2
  logger: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.0
  routemaster: ^0.10.0-dev2

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.0
  ficcanaso: ^2.0.7
  flutter_gen_runner: ^3.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  golden_toolkit: ^0.9.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  mocktail: ^0.1.4
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - dotenv
    - assets/logo/
    - assets/translations/

flutter_gen:
  output: lib/core/gen/
