name: flutter_starter_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.0.6+12
  bloc: ^8.0.1
  easy_localization: ^3.0.0
  firebase_core: ^1.10.0
  firebase_messaging: ^10.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.0
  json_annotation: ^4.1.0
  layout: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.1
  routemaster: ^0.10.0-dev5


dev_dependencies:
  artemis: ^7.1.1-beta.1
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  dante: ^0.0.4
  dart_code_metrics: ^4.1.0
  ficcanaso: ^3.0.8
  flutter_gen_runner: ^3.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  golden_toolkit: ^0.10.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  mocktail: ^0.2.0
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - dotenv
    - assets/logo/
    - assets/translations/

flutter_gen:
  output: lib/core/gen/
