name: flutter_starter_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.0.6+10
  bloc: ^7.2.0
  easy_localization: ^3.0.0
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  http: ^0.13.3
  injectable: ^1.4.1
  json_annotation: ^4.1.0
  layout: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.0
  routemaster: ^0.10.0-dev4

dev_dependencies:
  artemis: ^7.1.1-beta.1
  bloc_test: ^8.2.0
  build_runner: ^2.1.2
  dante: ^0.0.4
  dart_code_metrics: ^4.1.0
  ficcanaso: ^3.0.6
  flutter_gen_runner: ^3.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  golden_toolkit: ^0.10.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  mocktail: ^0.1.4
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - dotenv
    - assets/logo/
    - assets/translations/

flutter_gen:
  output: lib/core/gen/
