name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Create env file
        run: |
          touch dotenv
          echo ENDPOINT='https://graphql-pokemon2.now.sh/graphql' >> dotenv
          echo ENVIRONMENT='dev' >> dotenv
      - uses: erickzanardo/flutter-gh-pages@v6