name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Create env file
        run: |
          touch .env
          echo ENDPOINT='https://www.metaweather.com/' >> .env
      - uses: erickzanardo/flutter-gh-pages@v6