name: CI
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y lcov
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Create env file
      run: |
        touch dotenv
        echo ENDPOINT='https://graphql-pokemon2.now.sh/graphql' >> dotenv
        echo ENVIRONMENT='prod' >> dotenv
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: flutter test --coverage test/unit
    - run: lcov --remove coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' 'lib/*/*.graphql.dart' 'lib/*/*.part.dart' 'lib/core/gen/*.dart' 'lib/utils/constants/*.dart' 'lib/core/di/*.config.dart' 'lib/core/lang/*.dart' 'lib/feature/*/*/*_event.dart' 'lib/feature/*/*/*_state.dart' 'lib/feature/*/*/*_repo.dart' -o coverage/lcov.info
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage/lcov.info
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}